
```{r}
#----------testing our data curation by running JAGS on one subject

# Now we'll fit one subject just to make sure everything works

x <- x_all[1,]
X <- X_all[1,]

ntrials <- ntrials_all[1]

# set up jags and run jags model on one subject
data <- list("x","X","ntrials") 
params<-c("w","A","theta","a","p")
temp_samples <- jags.parallel(data, inits=NULL, params,
                model.file ="../utils/jags_PVL.txt",
                n.chains=3, n.iter=5000, n.burnin=1000, n.thin=1, n.cluster=4)
```




```{r}
for (i in 1:length(data)) {
df <- data_list[[i]]

x <- df$x
X <- df$X

n_subs <- n_distinct(df$Subj)

n_trials <- length(df$Subj)/n_subs

save_path <- paste('../estimations/', names(data_list)[i],'.rdata', sep = '')

  if (file.exists(save_path)) {
    # If the path exists, skip to the next iteration of the loop
    next
  }

# set up jags and run jags model
data <- list("x","X","n_trials","n_subs") 
params<-c("mu_w","mu_A","mu_theta","mu_a","lambda_w","lambda_A","lambda_theta","lambda_a")

start_time = Sys.time()
samples <- jags.parallel(data, inits=NULL, params,
                model.file ="../utils/hier_PVL.txt",
                n.chains=3, n.iter=5000, n.burnin=1000, n.thin=1, n.cluster=4)
end_time = Sys.time()
save(samples, file = save_path)
print(paste(names(data_list)[i],'complete. Elapsed time:', end_time - start_time))
}

```
