```{r setup}
# install.packages("pacman") 
pacman::p_load(tidyverse, R2jags, extraDistr)
source("functions.R")
source("PVL.R")
set.seed(69)
```

# Make decks
```{r}
n_trials <- 100
div <- 10

# Bad deck
# Large reward, frequent small loss
A <- create_deck(
  n_trials = n_trials,
  div = div,
  reward = 100,
  loss = -250,
  freq_of_loss = .5
)

# Bad deck
# Large reward, infrequent large loss
B <- create_deck(
  n_trials = n_trials,
  div = div,
  reward = 100, 
  loss = -1250,
  freq_of_loss = .1
)

# Good deck
# Small reward, frequent tiny loss
C <- create_deck(
  n_trials = n_trials,
  div = div,
  reward = 50, 
  loss = -50,
  freq_of_loss = .5
)

# Good deck
# Small reward, infrequent small loss
D <- create_deck(
  n_trials = n_trials,
  div = div,
  reward = 50,
  loss = -250,
  freq_of_loss = .1
)

payoff <- cbind(A, B, C, D) # combine
```

```{r}
# sanity check
head(payoff)
colSums(payoff) 
```

# Simulate

```{r}
w <- 2 # weighting parameter (aka. loss aversion)
A <- .5 # shape parameter (aka. risk aversion)
theta <- 3 # inverse heat parameter (aka. choice consitency)
a <- .1 # learning rate parameter (aka. prediction error weighting)
```

```{r}
PVL <- function(payoff,ntrials,w,A,a,theta) {
  
  # arrays to populate for simulation
  x <- array(NA,c(ntrials))
  X <- array(NA,c(ntrials))
  u <- array(NA,c(ntrials))
  Ev <- array(NA,c(ntrials,4))
  Ev_update <- array(NA,c(ntrials,4))
  exp_p <- array(NA,c(ntrials,4))
  p <- array(NA,c(ntrials,4))
  
  # free parameters - turn back on when constructing
  #w <- 2
  #A <- .5
  #a <- .1
  #theta <- 3
  #--- plot prospect theory function
  #x <- seq(1,100,1)
  #y <- x^A
  #plot(x,y)
  
  x[1] <- rcat(1,c(.25,.25,.25,.25)) # assigning a "flat" probability structure to the first choice (i.e. random choice between the four decks)
  
  X[1] <- payoff[1, x[1]] # assigning the payoff to first random choice
  
  Ev[1,] <- rep(0,4) # assigning zero as the expected value for all four decks at the first "random" choice 
  
  for (t in 2:ntrials) {
    
    u[t] <- ifelse(X[t-1]<0,-w*abs(X[t-1])^A,X[t-1]^A)
    
    for (d in 1:4) {
      
      Ev_update[t,d] <- Ev[t-1,d] + (a * (u[t] - Ev[t-1,d]))
      
      Ev[t,d] <- ifelse(x[t-1]==d,Ev_update[t,d],Ev[t-1,d])
      
      exp_p[t,d] <- exp(theta*Ev[t,d])
      
    }
    
    for (d in 1:4) {
      p[t,d] <- exp_p[t,d]/sum(exp_p[t,])
    }
    
    x[t] <- rcat(1,p[t,])
    
    X[t] <- payoff[t,x[t]]
    
  }
  
  result <- list(x=x,
                 X=X,
                 Ev=Ev)
  
  return(result)
  
  
  #turn back on when building
  #par(mfrow=c(2,2))
  #plot(Ev[,1])
  #plot(Ev[,2])
  #plot(Ev[,3])
  #plot(Ev[,4])
  #plot(x)
  
}
```

```{r}
PVL_sims <- PVL(payoff,n_trials,w,A,a,theta)
```


```{r}
par(mfrow=c(2,2))
plot(PVL_sims$Ev[,1], ylim=c(-1,1))
plot(PVL_sims$Ev[,2], ylim=c(-1,1))
plot(PVL_sims$Ev[,3], ylim=c(-1,1))
plot(PVL_sims$Ev[,4], ylim=c(-1,1))
title(paste("Traces of expeceted value (Ev) for all four decks over", n_trials, "trials"), line = -1, outer = TRUE)

x <- PVL_sims$x
X <- PVL_sims$X
```


