```{r setup}
install.packages("pacman")
pacman::p_load(tidyverse, R2jags, extraDistr)
source("../utils/simualte_PVL.R")
set.seed(69)
```

```{r}
# load payoff
payoff <- read.csv("../data/payoff.csv")
```

```{r}
n_trials <- len(payoff)
w <- 2 # weighting parameter (aka. loss aversion)
A <- .5 # shape parameter (aka. risk aversion)
theta <- 3 # inverse heat parameter (aka. choice consitency)
a <- .1 # learning rate parameter (aka. prediction error weighting)

PVL_sims <- PVL(payoff, n_trials, w, A, a, theta) # simulate
write.csv(PVL_sims, "../data/simulate.csv", row.names=FALSE)
```

```{r}
df <- tibble(
trial = 1:n_trials,
Ev_deck_1 = PVL_sims$Ev[,1],
Ev_deck_2 = PVL_sims$Ev[,2],
Ev_deck_3 = PVL_sims$Ev[,3],
Ev_deck_4 = PVL_sims$Ev[,4],
choice = PVL_sims$x,
payoff = PVL_sims$X)
print(df)
```


```{r}
df_long <- df %>%
  pivot_longer(cols = starts_with("Ev_deck"), names_to = "Deck", values_to = "EV") %>%
  mutate(Deck = factor(Deck, levels = c("Ev_deck_1", "Ev_deck_2", "Ev_deck_3", "Ev_deck_4"),
                       labels = c("Deck 1", "Deck 2", "Deck 3", "Deck 4")))
```


```{r}
ggplot(df_long, aes(x = trial, y = EV, color = Deck)) +
  geom_point() +
  theme_minimal() +
  labs(title = "Expected Value by Deck Over Trials",
       x = "Trial",
       y = "Expected Value",
       color = "Deck")

```



```{r}
ggplot(df_long, aes(x = trial, y = EV)) +
  geom_line(aes(color = Deck)) + # Use geom_line for continuous EV plot
  facet_wrap(~Deck, ncol = 2) + # Arrange plots in a 2x2 grid based on Deck
  theme_minimal() +
  labs(title = "Expected Value by Deck Over Trials",
       x = "Trial",
       y = "Expected Value") +
  theme(legend.position = "none") # Remove legend if not needed

```

